services:
  sqlserver:
    container_name: DepVis2-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - my_network

  depvisprocessing:
    build:
      context: ./DepVisBe
      dockerfile: ./DepVis.Processing/Dockerfile
    container_name: DepVis2-Processing
    depends_on:
      sqlserver:
        condition: service_started
    environment:
      - ConnectionStrings__Database=Server=sqlserver,1433;Database=depvisDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    networks:
      - my_network

  depviscore:
    build:
      context: ./DepVisBe
      dockerfile: ./DepVis.Core/Dockerfile
    container_name: DepVis2-Core
    depends_on:
      sqlserver:
        condition: service_started
    environment:
      - ConnectionStrings__Database=Server=sqlserver,1433;Database=depvisDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    networks:
      - my_network

  frontend:
    build:
      context: ./DepVisFe
      dockerfile: Dockerfile
    container_name: DepVis2-Frontend
    depends_on:
      - depviscore
    ports:
      - "8080:80"      # frontend now on http://localhost:8080
    networks:
      - my_network

  minio:
    image: minio/minio
    container_name: DepVis2-MinIO
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - my_network
    volumes:
      - "./minio-data:/data"

networks:
  my_network:
    driver: bridge

