services:
  sqlserver:
    container_name: DepVis2-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "127.0.0.1:1433:1433" 
    networks:
      - my_network

  depvisprocessing:
    build:
      context: ./Backend
      dockerfile: ./DepVis.Processing/Dockerfile
    container_name: DepVis2-Processing
    depends_on:
      sqlserver:
        condition: service_started
    environment:
        - ConnectionStrings__FrontEnd=http://147.251.115.226:8080
        - ConnectionStrings__Database=Server=sqlserver,1433;Database=depvisTest;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
        - ConnectionStrings__MinioEndpoint=minio
    networks:
      - my_network

  depviscore:
    build:
      context: ./Backend
      dockerfile: ./DepVis.Core/Dockerfile
    container_name: DepVis2-Core
    ports:
      - "5000:8080" 
    depends_on:
      sqlserver:
        condition: service_started
    environment:
      - ConnectionStrings__FrontEnd=http://147.251.115.226:8080
      - ConnectionStrings__Database=Server=sqlserver,1433;Database=depvisTest;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - ConnectionStrings__MinioEndpoint=minio
    networks:
      - my_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: ./dockerfile
      args:
        VITE_API_BASE_URL: "http://147.251.115.226:5000"
    container_name: DepVis2-Frontend
    depends_on:
      - depviscore
    ports:
      - "8080:80"
    networks:
      - my_network

  minio:
    image: minio/minio
    container_name: DepVis2-MinIO
    ports:
      - "127.0.0.1:9000:9000"   # S3 API
      - "127.0.0.1:9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - my_network
    volumes:
      - "./minio-data:/data"

networks:
  my_network:
    driver: bridge

