services:
  myservice:
    build:
      context: ./DepVisBe
      dockerfile: Dockerfile
    container_name: DepVis2-be
    ports:
      - "${SERVICE_PORT}:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=${SQL_SERVER},${SQL_PORT};Database=${SQL_DB};User Id=${SQL_USER};Password=${SA_PASSWORD};TrustServerCertificate=True
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: DepVis2-sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "${SQL_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql
      
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - "./minio-data:/data"

volumes:
  sql_data:
