services:
  sqlserver:
    container_name: DepVis2-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - my_network
  
  depvisprocessing:
    build:
      context: ./DepVisBe
      dockerfile: ./DepVisBe/DepVis.Processing/Dockerfile
    container_name: DepVis2-Processing
    environment:
      - ConnectionStrings__Database=Server=sqlserver,1433;Database=MyDatabase;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - my_network
      
  minio:
    image: minio/minio
    container_name: DepVis2-MinIO
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - my_network
    volumes:
      - "./minio-data:/data"

volumes:
  sql_data:


